# These are supported funding model platforms

# Support the author by using the funding Links below
# Developed and maintained by Waren Gonzaga with the help of awesome contributors.
# GitHub Sponsors: https://github.com/sponsors/iyashjayesh
# Buy Me a Coffee: https://buymeacoffee.com/codingyash
# Ko-fi: https://ko-fi.com/codingyash

github: iyashjayesh
ko_fi: codingyash
buy_me_a_coffee: codingyash

# Your support means a lot to me to continue the development of an open source project like this.
# Sponsoring this project means a lot to me. Your support helps me to continue building great
# open-source projects just like this.

# github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
# patreon: # Replace with a single Patreon username
# open_collective: # Replace with a single Open Collective username
# ko_fi: # Replace with a single Ko-fi username
# tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
# community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
# liberapay: # Replace with a single Liberapay username
# issuehunt: # Replace with a single IssueHunt username
# lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
# polar: # Replace with a single Polar username
# buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
# thanks_dev: # Replace with a single thanks.dev username
# custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
